name: "CI"

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Just
        uses: extractions/setup-just@v2

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: build
        run: |
          just --shell "bash" build
